"""add aircraft status fields

Revision ID: 0cc96c639e51
Revises: a27eb0b4b199
Create Date: 2026-05-20 21:00:11.556067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc96c639e51'
down_revision = 'a27eb0b4b199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###
